[package]
name = "wexplorer_infrastructure"
version = "0.1.0"
edition = "2021"

[dependencies]
tonic = { workspace = true }
config = { workspace = true }
tracing = { workspace = true }
tracing-log = { workspace = true }
tracing-subscriber = { workspace = true }